export const NFT_ARTWORKS = [
  {
    id: 'pixel-toad',
    label: 'Pixel Toad',
    image: '/nfts/01-pixel-toad.webp',
    palette: ['#071529', '#58c84f', '#d8f7ff'],
    motif: 'orbital',
  },
  {
    id: 'pixel-owl',
    label: 'Pixel Owl',
    image: '/nfts/02-pixel-owl.webp',
    palette: ['#211833', '#7655b5', '#f0a1ca'],
    motif: 'rings',
  },
  {
    id: 'blockhead',
    label: 'Blockhead',
    image: '/nfts/03-blockhead.webp',
    palette: ['#152235', '#f68b48', '#f4d154'],
    motif: 'signal',
  },
  {
    id: 'green-goblin',
    label: 'Green Goblin',
    image: '/nfts/04-green-goblin.webp',
    palette: ['#1e1531', '#72bd4c', '#efcf58'],
    motif: 'wave',
  },
  {
    id: 'neon-runner',
    label: 'Neon Runner',
    image: '/nfts/05-neon-runner.webp',
    palette: ['#050c17', '#ec4bb1', '#42e6ed'],
    motif: 'slash',
  },
  {
    id: 'sketch-avatar',
    label: 'Sketch Avatar',
    image: '/nfts/06-sketch-avatar.webp',
    palette: ['#ece8d2', '#7ba4c1', '#202020'],
    motif: 'portrait',
  },
  {
    id: 'red-hood',
    label: 'Red Hood',
    image: '/nfts/07-red-hood.webp',
    palette: ['#151b25', '#ca3846', '#63d8df'],
    motif: 'portrait',
  },
  {
    id: 'bitmap',
    label: 'Bitmap',
    image: '/nfts/08-bitmap.webp',
    palette: ['#090f19', '#ef4f83', '#50dfd5'],
    motif: 'blocks',
  },
  {
    id: 'space-penguin',
    label: 'Space Penguin',
    image: '/nfts/09-space-penguin.webp',
    palette: ['#0b1520', '#8bc9e8', '#f2eee1'],
    motif: 'ice',
  },
];
